# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Restore last saved session automatically when tmux server starts
set -g @continuum-restore 'on'

# Save interval in minutes (default is 15)
set -g @continuum-save-interval '15'

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
